<a href="https://colab.research.google.com/github/nilotpal-makes-stuff/TensorFlow-2-study/blob/main/youtube-ML_Zero_to_Hero/01Intro_to_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML Zero to Hero
Youtube - https://www.youtube.com/watch?v=KNAWp2S3w94&list=PLQY2H8rRoyvwWuPiWnuTDBHe7I0fMSsfO

## Introduction to Machine Learning

Consider equation
y = 2x-1

Lets construct two lists with values following this equation.

In [1]:
import random

start, end = -20, 20
size = 30

random.seed(10)

x_arr = [random.randint(start,end) for _ in range(size)]
y_arr = [2*x-1 for x in x_arr]

#x_arr = [-1,0,1,2,3,4]
#y_arr = [2*x-1 for x in x_arr]

#Normalise data
x_arr_norm = [x/20 for x in x_arr]
y_arr_norm = [y/41 if y<0 else y/39 for y in y_arr]

In [2]:
print(f"Values of 'x' : {x_arr}")
print(f"Values of 'y' : {y_arr}")


Values of 'x' : [16, -18, 7, 10, 16, -20, -7, 9, 11, -3, -10, -18, 13, 11, 0, -16, -5, 3, -18, 6, -12, 18, 2, 4, 6, -2, -4, 9, -9, -1]
Values of 'y' : [31, -37, 13, 19, 31, -41, -15, 17, 21, -7, -21, -37, 25, 21, -1, -33, -11, 5, -37, 11, -25, 35, 3, 7, 11, -5, -9, 17, -19, -3]


Using Keras **Sequential** model we can estimate the pattern which matches each number to the other.

In [3]:
import keras
import numpy

#Sequential model
seq_model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

#Compile the model
seq_model.compile(optimizer='sgd', loss='mean_squared_error')

#Convert data into numpy arrays
xs = numpy.array(x_arr_norm, dtype=float)
ys = numpy.array(y_arr_norm, dtype=float)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


For Sequential model, we are using **Dense** Layer which has one neuron (units=1) and data of shape [1].

We provide compiler with an 'optimizer' and a 'loss' parameter. Machine learning models make a guess as to what the function is which yields the output value we see. The model calculates how good or how bad a guess is using the **loss** function. It then uses the **optimiser** function to generate another guess.

The combination of the **loss** and the **optimiser** function will get us closer and closer to the actual function.

# Model fitting
**Model fitting** is the process of adjusting a machine learning model's internal parameters (such as weights and biases) to minimize the difference between its predictions and the actual target data, typically using optimization techniques.

**model.fit()** function is the primary method used to train a model by iterating over the dataset for a specified number of **epochs**, calculating **loss**, and updating **weights**.

The fitting process generally involves forward passes to generate predictions, loss calculation to measure error, and backward passes (backpropagation) to compute gradients for weight updates

In [4]:
num_epochs = 500
seq_model.fit(xs, ys, epochs=num_epochs)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 254ms/step - loss: 0.0756
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0747
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0738
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0728
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0719
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0710
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0702
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0693
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0684
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0676
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0667
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0659
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0651
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0643
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0635
Epoch 16/500
1/1 ━

**model.predict()** is a method used to generate predictions for new or unseen data after a model has been trained. It only needs the input data and returns the model's outputs, such as probabilities, class labels, or continuous values.

The method accepts input data in the form of NumPy arrays or TensorFlow datasets and processes them in batches, automatically handling inference mode (e.g., deactivating dropout layers). The structure of the output depends on the model's final layer.

In [5]:
test_arr = [10, 2, -3, 0]
#When training data is normalised - test data needs to be normalised
norm_test_arr = [i/20 for i in test_arr]

results = seq_model.predict(numpy.array(norm_test_arr, dtype=float))
#Denormalize the output
results = [i*39 if i>0 else i*41 for i in results]
#results = [i*40 for i in results]
results

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


[array([18.494757], dtype=float32),
 array([3.2842226], dtype=float32),
 array([-6.541456], dtype=float32),
 array([-0.5449958], dtype=float32)]